database kv config fix
error as follow:

Traceback (most recent call last):
File"/Users/nishenghao/aiops/fork-derisk/OpenDerisk/packages/derisk-core/src/derisk/util/configure/manager.py", Line 526, in _conv ert_value
File"/Users/nishenghao/aiops/fork-derisk/OpenDerisk/packages/derisk-core/src/derisk/util/configure/manager.py", line 604, in _conv ert_to_dataclass
prepared_field_values = prepare_data_func( concrete_cls, data)
File"/Users/nishenghao/aiops/fork-derisk/OpenDerisk/packages/derisk-core/src/derisk/util/configure/manager.py", line 591, in prepa re_data_func
raise ValueError (f"Missing required field: {fd. name}")
ValueError: Missing required field: database
During handling of the above exception, another exception occurred: